services:
    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
            args:
                UID: "${DOCKER_UID}"
        env_file:
            - .env
        volumes:
            - ..:/srv
        restart: "no"
