services:
    _defaults:
        autowire: true
        autoconfigure: true

    BaBeuloula\CloudImageProxy\Proxy:
        parent: 'BaBeuloula\CloudImageProxy\AbstractHandler'
        public: true

    BaBeuloula\CloudImageProxy\AbstractHandler: ~

    BaBeuloula\CloudImageProxy\Signer: ~

    BaBeuloula\CloudImageProxy\Twig\Extension\ProxyExtension: ~
