name: Code quality

on:
    push:
        branches:
            - '**'
            - '!main'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    composer:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Cache composer dependencies
                uses: actions/cache@v4
                with:
                    key: composer-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
                    restore-keys: composer-
                    path: vendor

            -   name: Install composer dependencies
                uses: php-actions/composer@v6
                with:
                    interaction: no
                    dev: yes
                    php_version: "8.2"
                    version: 2
                    args: --optimize-autoloader --no-scripts --ignore-platform-reqs

    changes:
        runs-on: ubuntu-latest

        outputs:
            lint: ${{ steps.filter.outputs.lint }}
            analyse: ${{ steps.filter.outputs.analyse }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   uses: dorny/paths-filter@v3
                id: filter
                with:
                    filters: |
                        lint:
                          - 'src/**'
                        analyse:
                          - 'src/**'

    lint:
        runs-on: ubuntu-latest

        needs: [composer,changes]

        if: ${{ needs.changes.outputs.lint == 'true' }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Cache composer dependencies
                uses: actions/cache@v4
                with:
                    key: composer-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
                    restore-keys: composer-
                    path: vendor

            -   name: PHP Code Sniffer
                run: make lint

    analyse:
        runs-on: ubuntu-latest

        needs: [composer,changes]

        if: ${{ needs.changes.outputs.analyse == 'true' }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Cache composer dependencies
                uses: actions/cache@v4
                with:
                    key: composer-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
                    restore-keys: composer-
                    path: vendor

            -   name: PHP Stan
                run: make analyse

    security:
        runs-on: ubuntu-latest

        needs: [composer,changes]

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Cache composer dependencies
                uses: actions/cache@v4
                with:
                    key: composer-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
                    restore-keys: composer-
                    path: vendor

            -   name: Audit composer dependencies
                uses: php-actions/composer@v6
                with:
                    interaction: no
                    dev: yes
                    php_version: "8.2"
                    version: 2
                    command: audit
